### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by ivkalita** [scukonick/gocloud#1]
What is the motivation behind this package? Why do we need it?

**Comment by ivkalita** [comment]
![image](https://user-images.githubusercontent.com/3984307/66717480-2cb59400-ede2-11e9-8205-209e802a5a5f.png)

**Comment by ghost** [comment]
**why not?**
![image](https://user-images.githubusercontent.com/15220500/66719204-7491e680-edf5-11e9-9b11-f03135b6d0a5.png)

**Comment by ivkalita** [comment]
Not bad
